export const EVENT_TYPES = {
  LOGIN_OR_SIGNUP_REQUEST: 'account/loginOrSignupRequest',
  LOGIN_OR_SIGNUP_SUCCESS: 'account/loginOrSignupSuccess',
  LOGIN_OR_SIGNUP_FAILURE: 'account/loginOrSignupFailure',
  LOGIN_REQUEST: 'account/loginRequest',
  LOGIN_SUCCESS: 'account/loginSuccess',
  LOGIN_FAILURE: 'account/loginFailure',
  SIGNUP_REQUEST: 'account/signupRequest',
  SIGNUP_SUCCESS: 'account/signupSuccess',
  SIGNUP_FAILURE: 'account/signupFailure',
  ACCOUNT_COMPLETION_REQUEST: 'account/accountCompletionRequest',
  ACCOUNT_COMPLETION_SUCCESS: 'account/accountCompletionSuccess',
  ACCOUNT_COMPLETION_FAILURE: 'account/accountCompletionFailure',
  DATA_REQUEST: 'dataRequest',
  DATA_SUCCESS: 'dataSuccess',
  DATA_FAILURE: 'dataFailure',
} as const
