export enum CharacteristicsEnum {
    ENERGETIC = 'ENERGETIC',
    CURIOUS = 'CURIOUS',
    SPORTY = 'SPORTY',
    CREATIVE = 'CREATIVE',
    FRIENDLY = 'FRIENDLY',
    TALKATIVE = 'TALKATIVE',
    CALM = 'CALM',
    PLAYFUL = 'PLAYFUL',
    FUNNY = 'FUNNY',
    INTELLIGENT = 'INTELLIGENT',
    AFFECTIONATE = 'AFFECTIONATE',
    INDEPENDENT = 'INDEPENDENT'
}